In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

## Create & Read

#### 1D Array

In [9]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape

(6,)

In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr1.ndim

1

In [14]:
arr1.size

6

#### 2D Array

In [15]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [18]:
arr2.shape #row, column

(2, 3)

In [19]:
arr2.dtype

dtype('int64')

In [20]:
arr2.size

6

#### 3D Array

In [25]:
arr3 = np.array([[[1,4,5],[6,7,4]], [[3,5,4],[5,8,7]], [[3,5,4],[5,8,7]] ])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [26]:
arr3.ndim

3

In [28]:
arr3.shape #number of layer, rows in each layer, columns in each layer

(3, 2, 3)

In [29]:
arr3.size

18

#### Create random Array

In [30]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.81797653, 0.99275453, 0.83943562],
        [0.95957645, 0.67755737, 0.45938256]],

       [[0.42483468, 0.09655836, 0.27050555],
        [0.48674874, 0.82213398, 0.09963051]],

       [[0.16645629, 0.99260669, 0.47626801],
        [0.65606021, 0.18916875, 0.24423395]]])

In [31]:
randomArr.dtype

dtype('float64')

In [35]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
zeros.ndim

3

In [37]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [38]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [42]:
arr3[0][0][2] #layer, row, column

np.int64(5)

In [45]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [46]:
arr3[-1]

array([[3, 5, 4],
       [5, 8, 7]])

In [47]:
arr3[1][0][1]

np.int64(5)

In [49]:
arr3[1,0,1]

np.int64(5)

## Update & Delete

In [51]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [52]:
a1

array([[[0.30285058, 0.07922245],
        [0.65440154, 0.02793672],
        [0.85161439, 0.68051088]],

       [[0.80011492, 0.92531065],
        [0.4599469 , 0.65075003],
        [0.7381508 , 0.18609503]]])

In [53]:
a2

array([[[0.30637333, 0.13799113],
        [0.85722312, 0.00879218],
        [0.98788511, 0.46387167]],

       [[0.80720538, 0.9902034 ],
        [0.83613895, 0.7492395 ],
        [0.37250365, 0.89881358]]])

#### Basic Math Operations

In [54]:
np.add(a1,a2)

array([[[0.60922391, 0.21721358],
        [1.51162466, 0.03672891],
        [1.8394995 , 1.14438255]],

       [[1.6073203 , 1.91551405],
        [1.29608585, 1.39998953],
        [1.11065445, 1.08490861]]])

In [55]:
np.subtract(a1,a2)

array([[[-0.00352274, -0.05876868],
        [-0.20282158,  0.01914454],
        [-0.13627072,  0.21663921]],

       [[-0.00709046, -0.06489276],
        [-0.37619205, -0.09848947],
        [ 0.36564714, -0.71271854]]])

In [56]:
np.divide(a1,a2)

array([[[0.9885018 , 0.57411262],
        [0.76339698, 3.17744907],
        [0.86205813, 1.46702401]],

       [[0.99121604, 0.93446523],
        [0.55008429, 0.86854741],
        [1.98159343, 0.2070452 ]]])

In [58]:
np.multiply(a1,a2)

array([[[9.27853404e-02, 1.09319948e-02],
        [5.60968133e-01, 2.45624810e-04],
        [8.41297176e-01, 3.15669720e-01]],

       [[6.45857072e-01, 9.16245751e-01],
        [3.84579521e-01, 4.87567625e-01],
        [2.74963870e-01, 1.67264742e-01]]])

#### Statistical operations

In [61]:
sqrt = np.sqrt(25)
abs = np.absolute(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
max = np.max(a2)

In [62]:
sqrt

np.float64(5.0)

In [63]:
abs

np.int64(2)

In [64]:
power

np.int64(256)

In [65]:
log

np.float64(3.2188758248682006)

In [66]:
mins

np.float64(0.027936720025402595)

In [67]:
max

np.float64(0.9902034035082269)

#### Updates the values

In [68]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [70]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  3,   5,   4],
        [  5,   8,   7]]])

In [71]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  3,   4,   5],
        [  5,   7,   8]]])

In [73]:
# Reshape
arr3.shape

(3, 2, 3)

In [74]:
arr3_reshape = arr3.reshape((2,3,3))

In [75]:
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  3,   4,   5],
        [  5,   7,   8]]])

In [76]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [77]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [81]:
appd = np.append(zeros,new_array,axis=0) #axis 0 is row, axis 1 is column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
# Insert

In [83]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [84]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
inserted_array = np.insert(zeros,1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [87]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.5082813 , 0.60050142, 0.52625105],
        [0.94426507, 0.46623682, 0.39113305]],

       [[0.04251515, 0.84823742, 0.62253934],
        [0.29438947, 0.81293767, 0.44973622]],

       [[0.0998205 , 0.7948296 , 0.06395251],
        [0.38367346, 0.97221865, 0.59787667]]])

In [91]:
# delete the array
arr5 = np.delete(arr4,0, axis=1)

In [90]:
arr5

array([[[0.94426507, 0.46623682, 0.39113305]],

       [[0.29438947, 0.81293767, 0.44973622]],

       [[0.38367346, 0.97221865, 0.59787667]]])

In [92]:
np.save("new_array",arr5)

In [93]:
np.load("new_array.npy")

array([[[0.94426507, 0.46623682, 0.39113305]],

       [[0.29438947, 0.81293767, 0.44973622]],

       [[0.38367346, 0.97221865, 0.59787667]]])